[tool.poetry]
name = "formula"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0"
django-import-export = "^3.3"
django-unfold = "^0.20.0"
whitenoise = "^6.6"
gunicorn = "^21.2"
django-money = "^3.4"
pillow = "^10.1"
django-debug-toolbar = "^4.2"
django-guardian = "^2.4"
django-simple-history = "^3.4"
sentry-sdk = { extras = ["django"], version = "^1.39" }
django-celery-beat = "2.1"
django-modeltranslation = "^0.18"
django-svelte-jsoneditor = "^0.4.0"

[tool.ruff]
fix = true
line-length = 88
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP", # pyupgrade
]
ignore = [
    "E501", # line too long, handled by black
    "B008", # do not perform function calls in argument defaults
    "C901", # too complex
]
exclude = ["**/migrations"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
